using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerHealth : MonoBehaviour
{
    public GameObject hud;
    //public GameObject inv;
    public GameObject deathScreen;
    public GameObject player;

    public float health = 100f;



    void Start()
    {
        deathScreen.SetActive(false);
    }



    void Update()
    {

        if(health <= 0)
        {
            player.SetActive(false);
            Cursor.visible = true;
            Cursor.lockState = CursorLockMode.None;
            hud.SetActive(false);
            //inv.SetActive(false);
            deathScreen.SetActive(true);
        }

        if (health > 100)
        {
            health = 100;
        }
        
    }
}
